stages:
  - build
  - deploy
  - deployPrd
  - deploytiny

variables:
  IMAGE_ADDRESS: $CI_REGISTRY_IMAGE:latest

build:staging:
  stage: build
  image: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f Dockerfile . -t $IMAGE_ADDRESS
    - docker push $IMAGE_ADDRESS

deploy:staging:
  stage: deploy
  when: manual
  #  when: manual
  needs:
    - build:staging
  image: kroniak/ssh-client
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh root@$SSH_HOST_STAGING 'cd /cytech/frontEnd/zarpal && docker compose pull web && docker compose up -d --remove-orphans'

deploy:production:
  stage: deployPrd
  when: manual
  needs:
    - build:staging
  image: kroniak/ssh-client
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # - ssh root@$SSH_HOST_PRODUCTION 'cd /root/zarpal && docker compose pull web && docker compose up -d --remove-orphans'

deploy:tiny:
  stage: deploytiny
  when: manual
  needs:
    - build:staging
  image: kroniak/ssh-client
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh root@$SSH_HOST_TINY 'cd /root/cytech/frontEnd/zarpal && docker compose pull web && docker compose up -d --remove-orphans'

